import psycopg2
from config import Config
from urllib.parse import urlparse
import sys

def create_subway_table():
    """
    Supabase DB에 realtime_subway_positions 테이블을 생성합니다.
    """
    conn = None
    cur = None
    
    # 1. 환경변수 및 설정 확인
    try:
        Config.check_config()
        if not Config.DATABASE_URL:
            print("❌ DATABASE_URL 환경변수가 설정되지 않았습니다.")
            return
    except ValueError as e:
        print(f"❌ 설정 오류: {e}")
        return

    # 2. DB 연결 시도
    try:
        dsn = Config.DATABASE_URL
        parsed = urlparse(dsn)
        # 비밀번호 마스킹 처리하여 출력
        masked_dsn = dsn.replace(parsed.password, "******") if parsed.password else dsn
        print(f"🔌 연결 정보: {masked_dsn}")
        
        print("⏳ 데이터베이스에 연결 중... (응답이 없으면 엔터를 쳐보세요)")
        conn = psycopg2.connect(dsn, connect_timeout=10)
        cur = conn.cursor()
        
        # 3. 테이블 생성 쿼리 (AGENT.md 및 docs/schema.sql 참고)
        # - direction_type, is_express: 데이터 타입 정합성을 위해 INTEGER 사용
        # - is_last_train: BOOLEAN 사용
        create_query = """
        CREATE TABLE IF NOT EXISTS realtime_subway_positions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            
            -- API 원본 데이터 매핑
            line_id VARCHAR(50),          -- subwayId
            line_name VARCHAR(50),        -- subwayNm
            station_id VARCHAR(50),       -- statnId
            station_name VARCHAR(100),    -- statnNm
            train_number VARCHAR(50),     -- trainNo
            last_rec_date VARCHAR(20),    -- lastRecptnDt
            last_rec_time VARCHAR(20),    -- recptnDt
            direction_type INTEGER,       -- updnLine (0/1)
            dest_station_id VARCHAR(50),  -- statnTid
            dest_station_name VARCHAR(100),-- statnTnm
            train_status VARCHAR(50),     -- trainSttus
            is_express INTEGER,           -- directAt (0/1/7)
            is_last_train BOOLEAN,        -- lstcarAt (0/1 -> T/F)
            
            created_at TIMESTAMPTZ DEFAULT NOW()
        );
        
        -- 인덱스 생성 (조회 성능 최적화)
        CREATE INDEX IF NOT EXISTS idx_subway_positions_created_at ON realtime_subway_positions(created_at);
        CREATE INDEX IF NOT EXISTS idx_subway_positions_line_id ON realtime_subway_positions(line_id);
        """
        
        # 4. 쿼리 실행
        cur.execute(create_query)
        conn.commit()
        
        print("✅ 테이블 'realtime_subway_positions' 생성이 완료되었습니다.")
        
    except psycopg2.OperationalError as e:
        print(f"\n❌ 데이터베이스 연결 오류: {e}")
        print("="*60)
        print("💡 [트러블슈팅 가이드]")
        print("1. 'could not translate host name' 오류가 발생한 경우:")
        print("   -> 현재 네트워크가 IPv6를 지원하지 않아 Supabase Direct URL에 접속하지 못할 수 있습니다.")
        print("   -> Supabase Dashboard > Project Settings > Database > Connection Pooling 에서")
        print("      'Connection Pooler (IPv4)' URL을 복사하여 .env의 DATABASE_URL을 업데이트하세요.")
        print("      (예: postgresql://postgres.[project]:[pwd]@aws-0-[region].pooler.supabase.com:6543/postgres)")
        print("2. 'password authentication failed' 오류가 발생한 경우:")
        print("   -> .env 파일의 DB 비밀번호가 올바른지 확인하세요.")
        print("="*60)
        
    except Exception as e:
        print(f"\n❌ 예상치 못한 오류 발생: {e}")
        if conn:
            conn.rollback()
            
    finally:
        if cur:
            cur.close()
        if conn:
            conn.close()

if __name__ == "__main__":
    create_subway_table()



