-- 테이블명: realtime_subway_positions
-- AGENT.md의 표준 스키마 정의에 따름

CREATE TABLE IF NOT EXISTS realtime_subway_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- API 원본 데이터 매핑
    line_id VARCHAR(50),          -- subwayId (지하철 호선 ID)
    line_name VARCHAR(50),        -- subwayNm (지하철 호선명)
    station_id VARCHAR(50),       -- statnId (지하철 역 ID)
    station_name VARCHAR(100),    -- statnNm (지하철 역명)
    train_number VARCHAR(50),     -- trainNo (열차 번호)
    last_rec_date VARCHAR(20),    -- lastRecptnDt (최종 수신 날짜)
    last_rec_time VARCHAR(20),    -- recptnDt (최종 수신 시간)
    direction_type VARCHAR(10),   -- updnLine (0:상행/내선, 1:하행/외선)
    dest_station_id VARCHAR(50),  -- statnTid (종착역 ID)
    dest_station_name VARCHAR(100), -- statnTnm (종착역명)
    train_status VARCHAR(10),     -- trainSttus (0:진입, 1:도착, 2:출발, 3:전전역출발 등)
    is_express VARCHAR(10),       -- directAt (1:급행, 0:아님, 7:특급)
    is_last_train VARCHAR(10),    -- lstcarAt (Boolean 변환 전 원본 저장 고려하여 VARCHAR 혹은 Boolean)
                                  -- 보통 API는 "0", "1"로 줌. 여기서는 VARCHAR로 받고 변환 로직은 Python에서 처리하거나
                                  -- DB에서 처리. AGENT.md에는 Boolean 변환이라 되어있으므로 Boolean으로 선언.
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 인덱스 설정 (조회 성능 최적화)
CREATE INDEX IF NOT EXISTS idx_subway_positions_created_at ON realtime_subway_positions(created_at);
CREATE INDEX IF NOT EXISTS idx_subway_positions_line_id ON realtime_subway_positions(line_id);
CREATE INDEX IF NOT EXISTS idx_subway_positions_station_id ON realtime_subway_positions(station_id);

COMMENT ON TABLE realtime_subway_positions IS '서울 지하철 실시간 열차 위치 모니터링 테이블';
